repos:
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: 91c5c7bcc8115b7b847300bf5f147158e497c342  # frozen: v1.3.0
  hooks:
  - id: insert-license
    files: '^src/.+\.py$|^tests/.+\.py$'
    args: ['--license-filepath', 'LICENSE-HEADER']
- repo: https://github.com/executablebooks/mdformat
  rev: b8c05ae822d53326e967da45367d0408afc56a81  # frozen: 0.7.14
  hooks:
  - id: mdformat
    additional_dependencies:
    - mdformat-toc
    - mdformat-gfm
    - mdformat-black
- repo: https://github.com/asottile/yesqa
  rev: 35cf7dc24fa922927caded7a21b2a8cb04bf8e10  # frozen: v1.3.0
  hooks:
  - id: yesqa
    additional_dependencies:
    - flake8-bugbear
    - flake8-builtins
    - flake8-comprehensions
- repo: https://github.com/MarcoGorelli/absolufy-imports
  rev: 1683a63d850e065495c05b771e4a20db010a58e7  # frozen: v0.3.1
  hooks:
  - id: absolufy-imports
    files: '^src/.+\.py$'
    args: ['--never', '--application-directories', 'src']
- repo: https://github.com/PyCQA/isort
  rev: c5e8fa75dda5f764d20f66a215d71c21cfa198e1  # frozen: 5.10.1
  hooks:
  - id: isort
- repo: https://github.com/psf/black
  rev: f6c139c5215ce04fd3e73a900f1372942d58eca0  # frozen: 22.6.0
  hooks:
  - id: black
- repo: https://github.com/myint/docformatter
  rev: 67919ee01837761f2d954d7fbb08c12cdd38ec5a  # frozen: v1.4
  hooks:
  - id: docformatter
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 3298ddab3c13dd77d6ce1fc0baf97691430d84b0  # frozen: v4.3.0
  hooks:
  - id: check-yaml
- repo: https://github.com/pre-commit/pygrep-hooks
  rev: 6f51a66bba59954917140ec2eeeaa4d5e630e6ce  # frozen: v1.9.0
  hooks:
  - id: python-use-type-annotations
  - id: python-check-blanket-noqa
  - id: python-check-blanket-type-ignore
- repo: https://github.com/PyCQA/flake8
  rev: cbeb4c9c4137cff1568659fcc48e8b85cddd0c8d  # frozen: 4.0.1
  hooks:
  - id: flake8
    additional_dependencies:
    - flake8-bugbear
    - flake8-builtins
    - flake8-comprehensions
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: efd441f735bae5b41a437713f667d6669415f6a0  # frozen: v0.961
  hooks:
  - id: mypy
    args: ["--scripts-are-modules"]
